name: CI + Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Auto-merge PR (squash) and delete branch
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: false
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000
          MERGE_LABELS: ""
