name: CI + Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  quality:
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Pint
        run: composer run lint

      - name: Run PHPStan
        run: composer run stan

  automerge:
    name: Auto-merge PR (squash) and delete branch
    runs-on: ubuntu-latest
    needs: quality
    if: github.event.pull_request.draft == false
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: false
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000
          MERGE_LABELS: ""
